spring:
  application:
    name: health-hub-db
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:health_hub_db
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
